CREATE TABLE IF NOT EXISTS compurooms (
  id SERIAL PRIMARY KEY,
  asset_code VARCHAR(50) NOT NULL,
  brand_model VARCHAR(100) NOT NULL,
  cpu VARCHAR(50) NOT NULL,
  ram_gb INT NOT NULL,
  room VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL
);